export const SET_LOGIN = 'SET_LOGIN';
export const RESPONSE_SUCCESS = 'RESPONSE_SUCCESS';
export const RESPONSE_ERROR = 'RESPONSE_ERROR';
export const CHANGE_INDEX_OF_QUESTIONS = 'CHANGE_INDEX_OF_QUESTIONS';
export const INCREASE_SCORE = 'INCREASE_SCORE';
export const CLEAR_GLOBAL_STATE = 'CLEAR_GLOBAL_STATE';
